{
 "title": "Dash Demo",
 "time": { "from": "2023-09-19T02:19:33.371Z", "to": "2023-09-19T02:33:49.802Z" },
 "panels": [
  {
   "title": "Pagamentos autorizados",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(idelta(init_auth[5m]))", "legendFormat": "total de auths" },
    { "expr": "sum(idelta(error_auth[5m]))", "legendFormat": "erros de auth" }
   ]
  },
  {
   "title": "Pagamentos",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "sum(idelta(init_payment[5m]))", "legendFormat": "total de pagamentos" },
    {
     "expr": "sum by(error) (idelta(error_payment{error=\"amount must be positive and greater than zero\"}[5m]))",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "sum by(error) (idelta(error_payment{error=\"error authorizing user\"}[5m]))",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "sum by(error) (idelta(error_payment{error=\"productId cannot be an empty string\"}[5m]))",
     "legendFormat": "{{error}}"
    },
    { "expr": "sum(idelta(error_payment[5m]))", "legendFormat": "total de erros" }
   ]
  },
  {
   "title": "TPV",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    { "expr": "sum(tpv)", "legendFormat": "tpv total" },
    {
     "expr": "sum by(productId) (tpv{productId=\"123\"})",
     "legendFormat": "{{productId}}"
    },
    {
     "expr": "sum by(productId) (tpv{productId=\"445\"})",
     "legendFormat": "{{productId}}"
    },
    {
     "expr": "sum by(productId) (tpv{productId=\"789\"})",
     "legendFormat": "{{productId}}"
    }
   ]
  },
  {
   "title": "TPV por produto",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tpv{productId=\"123\"}[5m])",
     "legendFormat": "{{productId}}"
    },
    {
     "expr": "rate(tpv{productId=\"445\"}[5m])",
     "legendFormat": "{{productId}}"
    },
    {
     "expr": "rate(tpv{productId=\"789\"}[5m])",
     "legendFormat": "{{productId}}"
    }
   ]
  },
  {
   "title": "TPV Hoje",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by() (tpv)", "legendFormat": "__auto" }
   ]
  }
 ]
}